// Initial seed data based on the portfolio's established content
export const initialProjects = [
  {
    _id: "proj-1",
    title: "MaaCubs Healthcare Ecosystem",
    techs: [
      "/assets/StackLogos/react.png",
      "/assets/StackLogos/tailwind.png",
      "/assets/StackLogos/express.png",
      "/assets/StackLogos/postgres.png",
      "/assets/StackLogos/node.png",
    ],
    technologies: "React, Tailwind, Express, PostgreSQL, Node",
    thumbnail: "/assets/ProjectThumbnails/maacubs.png",
    description: "Digital health platform for pregnancy trackers, pediatric vaccination schedules, and doctor consultations.",
    link: "https://maacubs.com/",
    detailedDescription: "A comprehensive digital health ecosystem designed for mothers, infants, and medical professionals. Built as a multi-tier platform, it includes a Flutter mobile application for patients & doctors, a React-based administration control center, and an Express/PostgreSQL API backend. The system automates child immunization tracking following clinical guidelines, milestone progression logs, pregnancy readiness roadmaps, and secure doctor credentials verification.",
    features: [
      "Dynamic App Version Control (Optional/Force update gating screen)",
      "Pediatric Vaccination Scheduling based on IAP Guidelines with mandatory/recommended categorization",
      "Developmental Milestones Checklist & automated developmental progress score generation",
      "Pregnancy Readiness Plan with support for checklist, rich-text, and video learning layouts",
      "Doctor Verification Workflow (Pending -> Approved/Rejected with license review)",
      "Online consultation fee billing powered by Razorpay payment gateway integration",
      "Targeted Push Notification Broadcasts filtered by trimester or baby age groups",
    ],
    techStack: [
      "Flutter",
      "React.js",
      "Node.js",
      "Express.js",
      "Prisma ORM",
      "PostgreSQL",
      "Razorpay",
      "Tailwind CSS",
    ],
    githubLink: "https://github.com/allindiacoderlife/maacubs.git",
    githubUrl: "https://github.com/allindiacoderlife/maacubs.git",
    liveDemo: "https://maacubs.com/",
    liveUrl: "https://maacubs.com/",
    category: "Healthcare",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "proj-2",
    title: "Spylt-GSAP Animation",
    techs: [
      "/assets/StackLogos/react.png",
      "/assets/StackLogos/gsap.jpg",
      "/assets/StackLogos/tailwind.png",
    ],
    technologies: "React, GSAP, Tailwind",
    thumbnail: "/assets/ProjectThumbnails/spyly.png",
    description: "Spylt Website",
    link: "https://spylt-gsap-animation.vercel.app/",
    detailedDescription: "A comprehensive e-commerce platform built with modern web technologies. Features include user authentication, product catalog, shopping cart, payment integration, and admin dashboard.",
    features: [
      "User Authentication",
      "Product Catalog",
      "Shopping Cart",
      "Payment Integration",
      "Admin Dashboard",
      "Responsive Design",
      "Real-time Data",
    ],
    techStack: ["React", "GSAP", "Tailwind"],
    githubLink: "https://github.com/allindiacoderlife/Spylt-Gsap-Animation.git",
    githubUrl: "https://github.com/allindiacoderlife/Spylt-Gsap-Animation.git",
    liveDemo: "https://spylt-gsap-animation.vercel.app/",
    liveUrl: "https://spylt-gsap-animation.vercel.app/",
    category: "E-Commerce",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "proj-3",
    title: "Insurance Management Platform",
    techs: [
      "/assets/StackLogos/react.png",
      "/assets/StackLogos/tailwind.png",
      "/assets/StackLogos/express.png",
      "/assets/StackLogos/postgres.png",
      "/assets/StackLogos/node.png",
    ],
    technologies: "React, Tailwind, Express, PostgreSQL, Node",
    thumbnail: "/assets/ProjectThumbnails/insurance.png",
    description: "Centralized system to digitize and simplify insurance operations",
    link: "https://insurance-management-platform-alpha.vercel.app",
    detailedDescription: "A comprehensive web-based application designed to digitize and simplify the management of insurance operations. It enables insurance companies, agents, and customers to manage policies, claims, premium payments, and related documents from a centralized and secure system.",
    features: [
      "User Roles & Permissions (Admin, Agent, Customer)",
      "Policy Management (Templates, Customer Policies)",
      "Claim Management with Attachment Proof Verification",
      "Premium Tracking & Payment Collection History",
      "Document Management (Identity & Policy Papers)",
      "Reports Dashboard with Metrics Visualizations",
    ],
    techStack: [
      "React 19",
      "Express.js",
      "Prisma ORM",
      "PostgreSQL",
      "Tailwind CSS",
      "Redis",
    ],
    githubLink: "https://github.com/allindiacoderlife/Insurance-Management-Platform.git",
    githubUrl: "https://github.com/allindiacoderlife/Insurance-Management-Platform.git",
    liveDemo: "https://insurance-management-platform-alpha.vercel.app/",
    liveUrl: "https://insurance-management-platform-alpha.vercel.app/",
    category: "Finance",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "proj-4",
    title: "Quiz Management Platform",
    techs: [
      "/assets/StackLogos/react.png",
      "/assets/StackLogos/tailwind.png",
      "/assets/StackLogos/express.png",
      "/assets/StackLogos/postgres.png",
      "/assets/StackLogos/node.png",
    ],
    technologies: "React, Tailwind, Express, PostgreSQL, Node",
    thumbnail: "/assets/ProjectThumbnails/quiz.png",
    description: "Secure role-based online exam & student assessment platform",
    link: "https://quiz-management-online-assessment-p.vercel.app/",
    detailedDescription: "A secure, full-stack, role-based online examination and student assessment web application. Designed to manage interactive category-specific quizzes, track student performance, display competitive leaderboards, and prevent client-side answer spoofing through secure backend validation.",
    features: [
      "Role-based authorization (Admin & Student roles)",
      "Email OTP-powered verification & registration logic",
      "Anti-cheat timed quiz engine (server-side scoring & key omission)",
      "Server-side timestamp-validated quiz attempt timers",
      "Comprehensive Admin CRUD dashboard for categories, questions & quizzes",
      "Gamified interactive student leaderboards & scoreboard history",
    ],
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "Drizzle ORM",
      "Tailwind CSS",
    ],
    githubLink: "https://github.com/allindiacoderlife/Quiz-Management---Online-Assessment-Platform.git",
    githubUrl: "https://github.com/allindiacoderlife/Quiz-Management---Online-Assessment-Platform.git",
    liveDemo: "https://quiz-management-online-assessment-p.vercel.app/",
    liveUrl: "https://quiz-management-online-assessment-p.vercel.app/",
    category: "Education",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "proj-5",
    title: "Nimbus Keyboards",
    techs: [
      "/assets/StackLogos/next.png",
      "/assets/StackLogos/react.png",
      "/assets/StackLogos/gsap.jpg",
      "/assets/StackLogos/tailwind.png",
    ],
    technologies: "Next, React, GSAP, Tailwind",
    thumbnail: "/assets/ProjectThumbnails/nimbus.png",
    description: "High-Performance Mechanical Keyboard Showcase & 3D Customizer",
    link: "https://nimbus-keyboards-dun.vercel.app/",
    detailedDescription: "An immersive, 3D e-commerce landing page and customizer experience built for high-end mechanical keyboards. The project blends modern frontend practices, interactive 3D rendering, and headless content management to deliver a premium user experience.",
    features: [
      "Interactive 3D Keyboard Customizer (React Three Fiber)",
      "Mechanical Switch Playground with realistic press animations",
      "Stripe payment gateway pipeline & serverless checkout",
      "Headless CMS integration via Prismic Slices",
      "Cinematic scrolling & camera transitions via GSAP ScrollTrigger",
      "Tactile audio-visual feedback synchronization",
    ],
    techStack: [
      "Next.js",
      "React Three Fiber",
      "GSAP",
      "Prismic CMS",
      "Stripe",
      "Tailwind CSS",
    ],
    githubLink: "https://github.com/allindiacoderlife/nimbus-keyboards.git",
    githubUrl: "https://github.com/allindiacoderlife/nimbus-keyboards.git",
    liveDemo: "https://nimbus-keyboards-dun.vercel.app/",
    liveUrl: "https://nimbus-keyboards-dun.vercel.app/",
    category: "E-Commerce",
    createdAt: new Date().toISOString(),
  },
];

export const initialCertificates = [
  {
    _id: "cert-1",
    title: "Full Stack Web Development",
    issuer: "freeCodeCamp",
    date: "2024",
    description: "Comprehensive course covering HTML, CSS, JavaScript, React, Node.js, and MongoDB",
    image: "/assets/certificates/fullstack-cert.svg",
    credentialId: "fcc-cert-001",
    skills: ["React", "Node.js", "MongoDB", "Express.js", "HTML", "CSS", "JavaScript"],
    verifyLink: "https://www.freecodecamp.org/certification/example/responsive-web-design",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "cert-2",
    title: "React Developer Certification",
    issuer: "Meta",
    date: "2024",
    description: "Advanced React concepts including hooks, context, state management, and testing",
    image: "/assets/certificates/react-cert.jpg",
    credentialId: "meta-react-001",
    skills: ["React", "Redux", "React Testing Library", "JavaScript", "TypeScript"],
    verifyLink: "https://www.coursera.org/account/accomplishments/certificate/example",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "cert-3",
    title: "JavaScript Algorithms and Data Structures",
    issuer: "freeCodeCamp",
    date: "2023",
    description: "Comprehensive study of algorithms, data structures, and problem-solving techniques",
    image: "/assets/certificates/js-algorithms-cert.jpg",
    credentialId: "fcc-js-001",
    skills: ["JavaScript", "Algorithms", "Data Structures", "Problem Solving"],
    verifyLink: "https://www.freecodecamp.org/certification/example/javascript-algorithms-and-data-structures",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "cert-4",
    title: "AWS Cloud Practitioner",
    issuer: "Amazon Web Services",
    date: "2024",
    description: "Foundational knowledge of AWS cloud services and best practices",
    image: "/assets/certificates/aws-cert.jpg",
    credentialId: "aws-cp-001",
    skills: ["AWS", "Cloud Computing", "EC2", "S3", "Lambda"],
    verifyLink: "https://aws.amazon.com/verification",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "cert-5",
    title: "MongoDB Developer Certification",
    issuer: "MongoDB University",
    date: "2023",
    description: "Database design, querying, indexing, and MongoDB best practices",
    image: "/assets/certificates/mongodb-cert.jpg",
    credentialId: "mongo-dev-001",
    skills: ["MongoDB", "Database Design", "Aggregation", "Indexing"],
    verifyLink: "https://university.mongodb.com/certification",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "cert-6",
    title: "UI/UX Design Fundamentals",
    issuer: "Google",
    date: "2023",
    description: "User experience design principles, prototyping, and user research methods",
    image: "/assets/certificates/ux-cert.jpg",
    credentialId: "google-ux-001",
    skills: ["UI/UX Design", "Figma", "Prototyping", "User Research"],
    verifyLink: "https://coursera.org/verify/google-ux",
    createdAt: new Date().toISOString(),
  },
];

export const initialSkills = [
  // Frontend
  { _id: "skill-1", name: "React", img: "/assets/StackLogos/react.png", category: "frontend" },
  { _id: "skill-2", name: "Sass", img: "/assets/StackLogos/sass.png", category: "frontend" },
  { _id: "skill-3", name: "Figma", img: "/assets/StackLogos/figma.png", category: "frontend" },
  { _id: "skill-4", name: "Tailwind", img: "/assets/StackLogos/tailwind.png", category: "frontend" },
  { _id: "skill-5", name: "Solid", img: "/assets/StackLogos/solidjs.png", category: "frontend" },
  { _id: "skill-6", name: "Astro", img: "/assets/StackLogos/astro.png", category: "frontend" },
  // Backend
  { _id: "skill-7", name: "Node", img: "/assets/StackLogos/node.png", category: "backend" },
  { _id: "skill-8", name: "Express", img: "/assets/StackLogos/express.png", category: "backend" },
  { _id: "skill-9", name: "Next", img: "/assets/StackLogos/next.png", category: "backend" },
  { _id: "skill-10", name: "Firebase", img: "/assets/StackLogos/firebase.png", category: "backend" },
  { _id: "skill-11", name: "Strapi", img: "/assets/StackLogos/strapi.png", category: "backend" },
  // Database
  { _id: "skill-12", name: "Postgres", img: "/assets/StackLogos/postgres.png", category: "database" },
  { _id: "skill-13", name: "MySQL", img: "/assets/StackLogos/mysql.png", category: "database" },
  { _id: "skill-14", name: "Mongo DB", img: "/assets/StackLogos/mongo.png", category: "database" },
  { _id: "skill-15", name: "Cloud Firestore", img: "/assets/StackLogos/firestore.png", category: "database" },
  { _id: "skill-16", name: "Supabase", img: "/assets/StackLogos/supabase.png", category: "database" },
  // Other
  { _id: "skill-17", name: "Git", img: "/assets/StackLogos/git.png", category: "other" },
  { _id: "skill-18", name: "AWS", img: "/assets/StackLogos/aws.png", category: "other" },
  { _id: "skill-19", name: "Google Cloud", img: "/assets/StackLogos/gcp.png", category: "other" },
  { _id: "skill-20", name: "Spline 3D", img: "/assets/StackLogos/spline.png", category: "other" },
  { _id: "skill-21", name: "Photoshop", img: "/assets/StackLogos/photoshop.png", category: "other" },
];

export const initialAbout = {
  name: "Chirag Saxena",
  greeting: "Hey mate! I'm",
  role: "Full-Stack Developer",
  roleSubtitle: "Ctrl + C De V eloper 😎",
  email: "chiragsaxena728@gmail.com",
  address: "Budaun",
  phone: "[+91] 89 2366 7469",
  nationality: "India",
  birthDate: "2005-02-10",
  gender: "Male",
  degree: "BTech. Artificial Intelligence & Data Science",
  institution: "G L Bajaj Group of Institutions, Mathura",
  story: "I've always been fascinated by technology and software development. I started my journey as a web-designer, but I realized that I wanted to be a full-stack developer. After pursuing higher education, I dedicated myself to building high-performance web applications, interactive 3D experiences, and production-grade architectures.",
  resumeUrl: "/resume.pdf",
};
